/**
 * テーマトークン定義
 * 画面全体で使う色・サーフェス・装飾用カラーを統一管理する。
 */

export const THEME_MODES = Object.freeze({
  LIGHT: 'light',
  DARK: 'dark',
  JOSHI: 'joshi',
  CYBER: 'cyber',
  NEON: 'neon',
});

const makeTheme = (tokens) => ({
  ...tokens,
  shadow: 'rgba(15, 23, 42, 0.16)',
  white: '#FFFFFF',
});

export const themeTokens = {
  [THEME_MODES.LIGHT]: makeTheme({
    background: '#EEF3FA',
    surface: '#FFFFFF',
    surfaceSecondary: '#F7FAFF',
    primary: '#1658B8',
    primaryVariant: '#0F4086',
    secondary: '#1E3A66',
    accent: '#0B9D8A',
    text: '#0F172A',
    textSecondary: '#516079',
    border: '#D7E2EF',
    divider: '#E5EDF7',
    error: '#C73D3D',
    success: '#157A4E',
    warning: '#C27B1C',
    info: '#1D70C9',
    drawerBackground: '#F4F8FF',
    drawerSurface: '#FFFFFF',
    headerBackground: '#FFFFFF',
    headerText: '#0F172A',
    subtleBackdrop: '#D9E6F7',
  }),
  [THEME_MODES.DARK]: makeTheme({
    background: '#0B1220',
    surface: '#111B2F',
    surfaceSecondary: '#17243B',
    primary: '#66A4FF',
    primaryVariant: '#3A7CE2',
    secondary: '#CEDAF0',
    accent: '#3ED2BF',
    text: '#ECF2FF',
    textSecondary: '#A8B7D2',
    border: '#223556',
    divider: '#1A2A46',
    error: '#FF7A7A',
    success: '#53CC94',
    warning: '#FFB458',
    info: '#73B8FF',
    drawerBackground: '#0E1729',
    drawerSurface: '#14213A',
    headerBackground: '#111B2F',
    headerText: '#F4F8FF',
    subtleBackdrop: '#18263E',
  }),
  [THEME_MODES.JOSHI]: makeTheme({
    background: '#FFF2F6',
    surface: '#FFFFFF',
    surfaceSecondary: '#FFEAF2',
    primary: '#D74684',
    primaryVariant: '#AF3068',
    secondary: '#6E355A',
    accent: '#FF8C73',
    text: '#4A1E3A',
    textSecondary: '#7A4A64',
    border: '#F3C9DA',
    divider: '#F9DDE8',
    error: '#D1495B',
    success: '#3E9C73',
    warning: '#D48B2D',
    info: '#5A7ED6',
    drawerBackground: '#FFF5F9',
    drawerSurface: '#FFFFFF',
    headerBackground: '#FFFFFF',
    headerText: '#4A1E3A',
    subtleBackdrop: '#FAD9E8',
  }),
  [THEME_MODES.CYBER]: makeTheme({
    background: '#071523',
    surface: '#0D2338',
    surfaceSecondary: '#11314A',
    primary: '#00CFFF',
    primaryVariant: '#00A9D8',
    secondary: '#88E9FF',
    accent: '#7BFFBD',
    text: '#E6FAFF',
    textSecondary: '#89C7D8',
    border: '#1D4665',
    divider: '#12324B',
    error: '#FF6E6E',
    success: '#49DFAE',
    warning: '#FFBF66',
    info: '#6BC9FF',
    drawerBackground: '#081E31',
    drawerSurface: '#10324C',
    headerBackground: '#0B2236',
    headerText: '#E6FAFF',
    subtleBackdrop: '#0D2A40',
  }),
  [THEME_MODES.NEON]: makeTheme({
    background: '#131117',
    surface: '#1D1A24',
    surfaceSecondary: '#262232',
    primary: '#FF7A1A',
    primaryVariant: '#E15E00',
    secondary: '#FFE8CD',
    accent: '#5EF08F',
    text: '#FFF8F0',
    textSecondary: '#D4C8B8',
    border: '#3B3447',
    divider: '#2E2940',
    error: '#FF7D7D',
    success: '#52D68F',
    warning: '#FFC266',
    info: '#8FC8FF',
    drawerBackground: '#16131E',
    drawerSurface: '#241F30',
    headerBackground: '#1F1B29',
    headerText: '#FFF8F0',
    subtleBackdrop: '#2A2536',
  }),
};

export const getThemeTokens = (mode) => themeTokens[mode] || themeTokens[THEME_MODES.LIGHT];
