/**
 * テーマトークン定義
 * 各テーマの色設定を管理
 */

export const THEME_MODES = {
  LIGHT: 'light',
  DARK: 'dark',
  JOSHI: 'joshi',
  CYBER: 'cyber',
  NEON: 'neon',
};

export const themeTokens = {
  [THEME_MODES.LIGHT]: {
    background: '#FFFFFF',
    surface: '#F5F5F5',
    primary: '#1976D2',
    primaryVariant: '#1565C0',
    secondary: '#424242',
    text: '#000000',
    textSecondary: '#666666',
    border: '#E0E0E0',
    error: '#D32F2F',
    success: '#388E3C',
    warning: '#FF9500',
    borderRadius: 8,
    shadowOpacity: 0.1,
    fontSize: {
      small: 12,
      medium: 14,
      large: 16,
      xlarge: 20,
    },
    fontWeight: 'normal',
    buttonStyle: 'solid',
  },
  [THEME_MODES.DARK]: {
    background: '#121212',
    surface: '#1E1E1E',
    primary: '#90CAF9',
    primaryVariant: '#64B5F6',
    secondary: '#BDBDBD',
    text: '#FFFFFF',
    textSecondary: '#B0B0B0',
    border: '#4A4A4A',
    error: '#EF5350',
    success: '#66BB6A',
    warning: '#FFB74D',
    borderRadius: 8,
    shadowOpacity: 0.3,
    fontSize: {
      small: 12,
      medium: 14,
      large: 16,
      xlarge: 20,
    },
    fontWeight: 'normal',
    buttonStyle: 'solid',
  },
  [THEME_MODES.JOSHI]: {
    background: '#FFF5F7',
    surface: '#FFE4E9',
    primary: '#FF69B4',
    primaryVariant: '#FF1493',
    secondary: '#8B4789',
    text: '#4A0E4E',
    textSecondary: '#8B4789',
    border: '#FFB6D9',
    error: '#DC143C',
    success: '#FF69B4',
    warning: '#FFB347',
    borderRadius: 20,
    shadowOpacity: 0.2,
    fontSize: {
      small: 13,
      medium: 15,
      large: 17,
      xlarge: 22,
    },
    fontWeight: '500',
    buttonStyle: 'rounded',
  },
  [THEME_MODES.CYBER]: {
    background: '#0A1929',
    surface: '#132F4C',
    primary: '#00D9FF',
    primaryVariant: '#00B8D4',
    secondary: '#FFD700',
    text: '#FFFFFF',
    textSecondary: '#B2BAC2',
    border: '#2E5A8A',
    error: '#FF4842',
    success: '#00D9FF',
    warning: '#FFB000',
    borderRadius: 4,
    shadowOpacity: 0.5,
    fontSize: {
      small: 11,
      medium: 13,
      large: 15,
      xlarge: 19,
    },
    fontWeight: '600',
    buttonStyle: 'angular',
  },
  [THEME_MODES.NEON]: {
    background: '#000000',
    surface: '#1A1A1A',
    primary: '#FF6B00',
    primaryVariant: '#E65100',
    secondary: '#00FF00',
    text: '#FFFFFF',
    textSecondary: '#CCCCCC',
    border: '#FF6B00',
    error: '#FF0000',
    success: '#00FF00',
    warning: '#FFB347',
    borderRadius: 0,
    shadowOpacity: 0.8,
    fontSize: {
      small: 12,
      medium: 14,
      large: 16,
      xlarge: 20,
    },
    fontWeight: 'bold',
    buttonStyle: 'neon',
  },
};

export const getThemeTokens = (mode) => {
  return themeTokens[mode] || themeTokens[THEME_MODES.LIGHT];
};
